version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: microitinerary-postgres
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_DB=microitinerary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microitinerary-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: microitinerary-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/microitinerary
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - microitinerary-net

volumes:
  postgres_data:


networks:
  microitinerary-net:
    driver: bridge
